version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Authenticate service account
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run: 
          name: 'Change service to deploy'
          command: sed 's/qa/'$GOOGLE_SERVICE'/g' app-example.yaml > app.yaml && cat app.yaml
      - run: 
          name: 'Deploy app'
          command: gcloud app deploy
workflows:
  build_my_app:
    jobs:
      - build
      - deploy
          requires: 
            - build