version: 2.1

orbs:
  node: circleci/node@5.0.2
  gcp-gcs: circleci/gcp-gcs@0.1.6

jobs:
  build:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            gcloud auth activate-service-account --key-file=$GCLOUD_SERVICE_KEY
            gsutil cp -r . gs://${GCLOUD_BUCKET}
          name: Copy files to GCP bucket